--Create users

INSERT INTO "user" (USER_ID, USER_EMAIL, USER_PASSWORD, USER_REGISTERED_ON, USER_ADMIN) 
  VALUES ('1', 'gmail', 'Ivan', TO_DATE('2017-10-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), false);
INSERT INTO "user" (USER_ID, USER_EMAIL, USER_PASSWORD, USER_REGISTERED_ON, USER_ADMIN)
  VALUES ('2', 'ukrnet', 'Petro', TO_DATE('2007-09-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), false);
  INSERT INTO "user" (USER_ID, USER_EMAIL, USER_PASSWORD, USER_REGISTERED_ON, USER_ADMIN) 
  VALUES ('3', 'mailru', 'Vasyl', TO_DATE('2017-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), false);
INSERT INTO "user" (USER_ID, USER_EMAIL, USER_PASSWORD, USER_REGISTERED_ON, USER_ADMIN)
  VALUES ('4', 'yandex', 'Dima', TO_DATE('2017-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), false);

--Create students
INSERT INTO "student" (STUDENT_ID, STUDENT_EMAIL, FIRST_NAME, SECOND_NAME)
  VALUES ('1', 'gmail', 'Ivan', 'QWERTY');
INSERT INTO "student" (STUDENT_ID, STUDENT_EMAIL, FIRST_NAME, SECOND_NAME)
  VALUES ('2', 'ukrnet', 'Petro', 'ASDFGH');
INSERT INTO "student" (STUDENT_ID, STUDENT_EMAIL, FIRST_NAME, SECOND_NAME)
  VALUES ('3', 'mailru', 'Vasyl', 'IUHGIUGGI');
INSERT INTO "student" (STUDENT_ID, STUDENT_EMAIL, FIRST_NAME, SECOND_NAME)
  VALUES ('4', 'yandex', 'Dima', 'JKHJKHKJH');

--Create groups
INSERT INTO "group" (GROUP_ID, GROUP_NAME) 
  VALUES ('1', 'KM1111');
INSERT INTO "group" (GROUP_ID, GROUP_NAME) 
  VALUES ('2', 'KM2222');
INSERT INTO "group" (GROUP_ID, GROUP_NAME) 
  VALUES ('3', 'KM3333');
INSERT INTO "group" (GROUP_ID, GROUP_NAME) 
  VALUES ('4', 'KM4444');
  
--Create faculties
INSERT INTO "faculty" (FACULTY_ID, FACULTY_NAME) 
  VALUES ('1', 'MMMMMMMMM');
INSERT INTO "faculty" (FACULTY_ID, FACULTY_NAME) 
  VALUES ('2', 'JJJJJJJJJ');
INSERT INTO "faculty" (FACULTY_ID, FACULTY_NAME) 
  VALUES ('3', 'JIHKJHJJJ');
INSERT INTO "faculty" (FACULTY_ID, FACULTY_NAME) 
  VALUES ('4', 'FXTFTFCYCGY');
  
--Create universities
INSERT INTO "university" (UNIVER_ID, UNIVER_NAME) 
  VALUES ('1', 'KPI');
INSERT INTO "university" (UNIVER_ID, UNIVER_NAME) 
  VALUES ('2', 'KNU');
INSERT INTO "university" (UNIVER_ID, UNIVER_NAME) 
  VALUES ('3', 'NAU');
INSERT INTO "university" (UNIVER_ID, UNIVER_NAME) 
  VALUES ('4', 'KNEU');