CREATE TABLE UNIVERSITY (
  UNIVERSITY_NAME VARCHAR2(30),
  CONSTRAINT PK_UNIVERSE PRIMARY KEY (UNIVERSITY_NAME)
);

CREATE TABLE FACULTY (
  FACULTY_NAME VARCHAR2(30),
  CONSTRAINT PK_FACULTY PRIMARY KEY (FACULTY_NAME)
);

CREATE TABLE ST_GROUP (
  GROUP_NAME VARCHAR2(30),
  GROUP_YEAR NUMBER(4),
  CONSTRAINT PK_GROUP PRIMARY KEY (GROUP_NAME)
);

CREATE TABLE UNI_USER (
  USER_LOGIN VARCHAR2(8) NOT NULL,
  USER_PASSWORD VARCHAR2(30) NOT NULL,
  USER_EMAIL VARCHAR2(30) NOT NULL,
  STATUS VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_LOGIN)
);

CREATE TABLE STUDENT (
  STUDENT_FIRST_NAME VARCHAR2(15) NOT NULL,
  STUDENT_LAST_NAME VARCHAR2(15) NOT NULL,
  UNIVERSITY_NAME VARCHAR2(30) NOT NULL,
  FACULTY_NAME VARCHAR2(30) NOT NULL,
  GROUP_NAME VARCHAR2(30) NOT NULL
);


ALTER TABLE STUDENT ADD CONSTRAINT FK__ST_UNIVERSITY
FOREIGN KEY (UNIVERSITY_NAME) REFERENCES UNIVERSITY (UNIVERSITY_NAME);

ALTER TABLE STUDENT ADD CONSTRAINT FK_ST_FACULTY
FOREIGN KEY (FACULTY_NAME) REFERENCES FACULTY (FACULTY_NAME);

ALTER TABLE STUDENT ADD CONSTRAINT FK__ST_GROUP
FOREIGN KEY (GROUP_NAME) REFERENCES ST_GROUP (GROUP_NAME);