--Create users
  
INSERT INTO UNI_USER (USER_LOGIN, USER_PASSWORD, USER_EMAIL, STATUS)
VALUES('happy007', 'uibsgfz56','gmail','ADMIN');
INSERT INTO UNI_USER (USER_LOGIN, USER_PASSWORD, USER_EMAIL, STATUS)
VALUES ('unicorn99', 'tgvdfd','gmail','NOT_AMDIN');
INSERT INTO UNI_USER (USER_LOGIN, USER_PASSWORD, USER_EMAIL, STATUS)
VALUES ('4everbestprofessor', '9jsfg','gmail','NOT_AMDIN');
INSERT INTO UNI_USER (USER_LOGIN, USER_PASSWORD, USER_EMAIL, STATUS)
VALUES ('pythongod', 'u7ihbvs','gmail','AMDIN');
INSERT INTO UNI_USER (USER_LOGIN, USER_PASSWORD, USER_EMAIL, STATUS)
VALUES ('superman', 'yhg7hnsf','gmail','NOT_AMDIN');

--Create students

INSERT INTO STUDENT (STUDENT_FIRST_NAME, STUDENT_LAST_NAME, UNIVERSITY_NAME, FACULTY_NAME, GROUP_NAME)
  VALUES ('Ivan', 'QWERTY', 'KPI', 'MMMMMMMMM', 'KM1111');
INSERT INTO STUDENT (STUDENT_FIRST_NAME, STUDENT_LAST_NAME)
  VALUES ('Petro', 'ASDFGH', 'KPI', 'MMMMMMMMM', 'KM1111');
INSERT INTO STUDENT (STUDENT_FIRST_NAME, STUDENT_LAST_NAME)
  VALUES ('Vasyl', 'IUHGIUGGI', 'KPI', 'MMMMMMMMM', 'KM1111');
INSERT INTO STUDENT (STUDENT_FIRST_NAME, STUDENT_LAST_NAME)
  VALUES ('Dima', 'JKHJKHKJH', 'KPI', 'MMMMMMMMM', 'KM1111');

--Create groups

INSERT INTO ST_GROUP (GROUP_NAME, GROUP_YEAR) 
  VALUES ('KM1111','2011');
INSERT INTO ST_GROUP (GROUP_NAME, GROUP_YEAR) 
  VALUES ('KM2222','2012');
INSERT INTO ST_GROUP (GROUP_NAME, GROUP_YEAR) 
  VALUES ('KM3333','2013');
INSERT INTO ST_GROUP (GROUP_NAME, GROUP_YEAR) 
  VALUES ('KM4444','2014');
  
--Create faculties

INSERT INTO FACULTY (FACULTY_NAME) 
  VALUES ('MMMMMMMMM');
INSERT INTO FACULTY (FACULTY_NAME) 
  VALUES ('JJJJJJJJJ');
INSERT INTO FACULTY (FACULTY_NAME) 
  VALUES ('JIHKJHJJJ');
INSERT INTO FACULTY (FACULTY_NAME) 
  VALUES ('FXTFTFCYCGY');
  
--Create universities

INSERT INTO UNIVERSITY (UNIVERSITY_NAME) 
  VALUES ('KPI');
INSERT INTO UNIVERSITY (UNIVERSITY_NAME) 
  VALUES ('KNU');
INSERT INTO UNIVERSITY (UNIVERSITY_NAME) 
  VALUES ('NAU');
INSERT INTO UNIVERSITY (UNIVERSITY_NAME) 
  VALUES ('KNEU');