CREATE OR REPLACE PACKAGE USER_PACKAGE AS
  TYPE T_USER IS RECORD (
  USER_NAME VARCHAR2(30 CHAR),
  USER_EMAIL VARCHAR2(30 CHAR),
  USER_PASSWORD VARCHAR2(30 CHAR),
  REGISTERED_ON VARCHAR2(30 CHAR)
);

TYPE T_USER_TABLE IS TABLE OF T_USER;

FUNCTION LOG_IN(USER_EMAIL IN USERS.USER_EMAIL%TYPE, USER_PASSWORD IN USERS.USER_PASSWORD%TYPE)
RETURN T_USER_TABLE PIPELINED;

PROCEDURE REGISTER(USER_NAME     IN USERS.USER_NAME%TYPE,
USER_EMAIL    IN USERS.USER_EMAIL%TYPE,
USER_PASSWORD    IN USERS.USER_PASSWORD%TYPE);
END;

CREATE OR REPLACE PACKAGE BODY USER_PACKAGE AS
FUNCTION LOG_IN(USER_EMAIL IN USERS.USER_EMAIL%TYPE)
RETURN T_USER_TABLE PIPELINED AS
CURSOR MY_CUR IS
SELECT *
FROM USERS
WHERE USERS.USER_EMAIL = USER_EMAIL AND USERS.USER_PASSWORD = USER_PASSWORD;
BEGIN
FOR rec IN MY_CUR
LOOP
pipe row (rec);
end loop;
END;

PROCEDURE REGISTER(USER_NAME     IN USERS.USER_NAME%TYPE,
USER_EMAIL    IN USERS.USER_EMAIL%TYPE,
USER_PASSWORD    IN USERS.USER_PASSWORD%TYPE) AS
BEGIN
INSERT INTO USERS (USER_NAME, USER_EMAIL, USER_PASSWORD, REGISTERED_ON) VALUES (USER_NAME, USER_EMAIL, USER_PASSWORD, NOW());
END;

END;
/

SELECT *
FROM TABLE (USER_PACKAGE.REGISTER('Gray', 'sdgsdgs@fasfas.com', '12341234'));
