CREATE OR REPLACE PACKAGE STUDENT_INFO_PACKAGE AS
TYPE T_STUDENT IS RECORD (
STUDENT_ID Number,
USER_ID Number,
FIRST_NAME VARCHAR2(255 CHAR),
SECOND_NAME VARCHAR2(255 CHAR),
EMAIL VARCHAR2(255 CHAR),
GROUP_ID Number,
GROUP_NAME VARCHAR2(255 CHAR),
FACULTY_ID Number,
FACULTY_NAME VARCHAR2(255 CHAR),
UNIVERSITY_ID Number,
UNIVERSITY_NAME VARCHAR2(255 CHAR)
);

TYPE T_USER_TABLE IS TABLE OF T_USER;

FUNCTION GET_STUDENT_INFO(USER_ID IN USERS.USER_ID%TYPE, STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE)
RETURN T_STUDENT PIPELINED;

CREATE OR REPLACE PACKAGE BODY STUDENT_INFO_PACKAGE AS
FUNCTION GET_STUDENT_INFO(USER_ID IN USERS.USER_ID%TYPE, STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE)
RETURN T_STUNDET PIPELINED AS
CURSOR MY_CUR IS
SELECT s.STUDENT_ID, u.USER_ID, s.FIRST_NAME, s.SECOND_NAME, s.EMAIL, g.GROUP_ID, g.GROUP_NAME, f.FACULTY_ID, f.FACULTY_NAME, u.UNIVERSITY_ID, u.UNIVERSITY_NAME
  FROM USERS u
  JOIN STUDENTS s
  JOIN GROUP g
  JOIN FACULTY f
  JOIN UNIVERSITY u
WHERE USERS.USER_ID = USER_ID AND STUDENTS.STUDENT_ID = STUDENT_ID;
BEGIN
FOR rec IN MY_CUR
LOOP
pipe row (rec);
end loop;
END;

END;

SELECT * FROM TABLE (STUDENT_INFO_PACKAGE.GET_STUDENT_INFO(1, 1));
