CREATE OR REPLACE PACKAGE UNIVERSITY_PACKAGE AS  
  
TYPE UNIVERSITY_INFO_RECORD IS RECORD (  
  
    UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE  
  
);  
  
TYPE UNIVERSITY_INFO_TABLE IS   
    TABLE OF UNIVERSITY_INFO_RECORD;  
  
  
    FUNCTION GET_UNIVERSITY_INFO  
    RETURN UNIVERSITY_INFO_TABLE PIPELINED;  
  
	  
    PROCEDURE ADD_UNIVERSITY(  
        UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE  
    );  
      
    PROCEDURE UPDATE_UNIVERSITY_NAME(  
        UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE,
        ST_UNIVER_NAME     STUDENT.UNIVERSITY_NAME%TYPE
    );  
  
    PROCEDURE DELETE_UNIVERSITY( 
        UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE
    ); 
     
END UNIVERSITY_PACKAGE;
/

CREATE OR REPLACE PACKAGE BODY UNIVERSITY_PACKAGE IS  
  
    FUNCTION GET_UNIVERSITY_INFO  
    RETURN UNIVERSITY_INFO_TABLE   
        PIPELINED  
    IS  
    BEGIN  
    FOR PIECE IN (  
        SELECT DISTINCT  UNIVERSITY_NAME  
        FROM UNIVERSITY 
    ) LOOP  
        PIPE ROW (PIECE);  
    END LOOP;  
    END GET_UNIVERSITY_INFO;  
      
      
    PROCEDURE ADD_UNIVERSITY(  
        UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE   
    )  
    IS  
    BEGIN  
	INSERT INTO UNIVERSITY (UNIVERSITY_NAME)  
    VALUES (UNIVER_NAME);  
    COMMIT;  
    END ADD_UNIVERSITY;  
  
    PROCEDURE UPDATE_UNIVERSITY_NAME(  
        UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE,
        ST_UNIVER_NAME     STUDENT.UNIVERSITY_NAME%TYPE
    )  
    IS  
    BEGIN  
    UPDATE UNIVERSITY
    SET UNIVERSITY.UNIVERSITY_NAME = UNIVER_NAME  
    WHERE STUDENT.UNIVERSITY_NAME = ST_UNIVER_NAME;  
    COMMIT;  
    END UPDATE_UNIVERSITY_NAME;  
      
    PROCEDURE DELETE_UNIVERSITY( 
        UNIVER_NAME        UNIVERSITY.UNIVERSITY_NAME%TYPE   
    ) 
    IS 
    BEGIN 
    DELETE FROM UNIVERSITY 
    WHERE UNIVERSITY.UNIVERSITY_NAME  = UNIVER_NAME; 
    COMMIT; 
    END DELETE_UNIVERSITY; 
 
 
END UNIVERSITY_PACKAGE;  
/

BEGIN
    UNIVERSITY_PACKAGE.UPDATE_UNIVERSITY_NAME('PKI', 'KPI');
END;
/

SELECT * from UNIVERSITY;


